## library() calls go here
library(arrow)
library(conflicted)
library(dotenv)
library(geoarrow)
library(geodata)
library(geotargets)
library(targets)
library(tarchetypes)
library(terra)
library(wk)
library(quarto)
